# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4031f2d87f6da4a584c88ec37a85a012a9fafd02ce4dee2f5ea49061b0baa8cb094419d37ec4563a556fba4023b4647cec7f31a7492c3cb118196b37405a1158

test:
  secret_key_base: 5103e599a00ea69a031cdcedc20c505c12a8dc1002999c725c1bb372747ebff6958b0f6e94b9be7f38632eb147126217ea20211d422242fca97a060e15ea1442

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
